### ISSUE TITLE
BFV multiplication gives incorrect result for large polynomials

### ISSUE THREAD

**Issue by sarojaduality** [openfheorg/openfhe-development#111]
In the bgv-bfv-benchmarks branch, if we run the bgv-bfv-benchmarks for the Polynomial demo, there are some incorrect results for degree 48 and 64 polynomials for HPS and BEHZ. It looks like the noise level reaches 58, while the modulus is 60. Maybe there is a bug in BFV moduli selection in ParamsGen.

**Comment by yspolyakov** [comment]
Seems like a potentially valid issue as our current BFV estimates are based on binary tree evaluation, and do not consider the effect of many additions, which occur during polynomial evaluation. We will need a good example that manifests the issue to adjust the estimates in BFV for the cases with many additions and multiplications.

**Comment by sarojaduality** [comment]
The bug occurs when we set both EvalMultCount and EvalAddCount to be nonzero. Currently the BFVrns ParamsGen logic only selects moduli when exactly one of EvalMultCount, EvalAddCount, and KeySwitchCount is nonzero.

**Comment by yspolyakov** [comment]
Add an exception is the user specifies both MultDepth and EvalAddCount/KeySwitchCount

**Comment by dsuponitskiy** [comment]
Also, the type of EvalMultCount, EvalAddCount, and KeySwitchCount will change from int32_t to uint32_t as they cannot have negative values.

**Comment by dsuponitskiy** [comment]
The fix is in the dev branch.
