### ISSUE TITLE
Add entries for N = 64K to the security tables for LWE

### ISSUE THREAD

**Issue by yspolyakov** [openfheorg/openfhe-development#147]
http://homomorphicencryption.org/wp-content/uploads/2018/11/HomomorphicEncryptionStandardv1.1.pdf does not include entries for $N = 2^{16}$ and $N=2^{17}$. We need to run estimation using https://github.com/malb/lattice-estimator and update the tables in OpenFHE.

**Comment by 604254229** [comment]
https://github.com/malb/lattice-estimator  .This is the evaluation tool we used to assess the security strength. When selecting the ring dimension of 65536 and q_bit_length of 2253 as parameters, the security strength was evaluated to be between 60 and 80, which does not meet the requirement of HEStd_128_classic.
CKKS scheme is using ring dimension 65536
Moduli chain of pk:
q_0: 1152921504606584833, log q_0: 60
q_1: 576460752405135361, log q_1: 59
q_2: 576460752395960321, log q_2: 59
q_3: 576460752399106049, log q_3: 59
q_4: 576460752284418049, log q_4: 59
q_5: 576460752347332609, log q_5: 59
q_6: 576460752286253057, log q_6: 59
q_7: 576460752319414273, log q_7: 59
q_8: 576460752289005569, log q_8: 59
q_9: 576460752347201537, log q_9: 59
q_10: 576460752289529857, log q_10: 59
q_11: 576460752315482113, log q_11: 59
q_12: 576460752289923073, log q_12: 59
q_13: 576460752342876161, log q_13: 59
q_14: 576460752298180609, log q_14: 59
q_15: 576460752340123649, log q_15: 59
q_16: 576460752321642497, log q_16: 59
q_17: 576460752337502209, log q_17: 59
q_18: 576460752325705729, log q_18: 59
q_19: 576460752331210753, log q_19: 59
q_20: 576460752329113601, log q_20: 59
q_21: 576460752329900033, log q_21: 59
q_22: 576460752328327169, log q_22: 59
q_23: 576460752329506817, log q_23: 59
q_24: 576460752298835969, log q_24: 59
q_25: 576460752319021057, log q_25: 59
q_26: 576460752300015617, log q_26: 59
q_27: 576460752308273153, log q_27: 59
q_28: 1152921504598720513, log q_28: 60
q_29: 1152921504597016577, log q_29: 60
q_30: 1152921504595968001, log q_30: 60
q_31: 1152921504592822273, log q_31: 60
q_32: 1152921504592429057, log q_32: 60
q_33: 1152921504589938689, log q_33: 60
q_34: 1152921504586530817, log q_34: 60
q_35: 1152921504583647233, log q_35: 60
q_36: 1152921504581419009, log q_36: 60
q_37: 1152921504580894721, log q_37: 60
Total bit length: 2253

**Comment by yspolyakov** [comment]
Adding entries for $N=2^17$ is problematic. See https://github.com/malb/lattice-estimator/issues/75 for more details. So we will update only the tables for $N=2^16$ for now.
