### ISSUE TITLE
Apply bugfixes from PALISADE v1.11.7

### ISSUE THREAD

**Issue by yspolyakov** [openfheorg/openfhe-development#149]
The following bugfixes from v1.11.7 (https://gitlab.com/palisade/palisade-development/-/milestones/22#tab-issues) also need to be applied to OpenFHE:
* https://gitlab.com/palisade/palisade-development/-/merge_requests/394
* https://gitlab.com/palisade/palisade-development/-/merge_requests/393
* https://gitlab.com/palisade/palisade-development/-/merge_requests/395
* https://gitlab.com/palisade/palisade-development/-/merge_requests/389
* https://gitlab.com/palisade/palisade-development/-/merge_requests/387
* https://gitlab.com/palisade/palisade-development/-/merge_requests/388

**Comment by dsuponitskiy** [comment]
The work is done. All code changes are in the dev branch.
