### ISSUE TITLE
Dockerfile does not work [bug]

### ISSUE THREAD

**Issue by Superkaki** [openfheorg/openfhe-development#154]
Dockerfile has an old git path, branch and tag. It worked for me this way:
- git path = _openfheorg_ insted of _openfhe_
- branch = _main_ insted of _master_
- tag = _v0.9.1_ insted of _master_

**Comment by dsuponitskiy** [comment]
Fixed.
Note: @Superkaki, you would want to manually change the tag in your local Dockerfile if you want to build an image with a different tag.
