### ISSUE TITLE
Cannot Serialize Relinearization Key

### ISSUE THREAD

**Issue by sofianeazogagh** [openfheorg/openfhe-development#175]
When I want to serialize the EvalMultKey or EvalAutomorphismKey exactly like in "simple-real-numbers-serial.cpp" I get this error :

libc++abi: terminating with uncaught exception of type cereal::Exception: Trying to save an unregistered polymorphic type (lbcrypto::EvalKeyRelinImpl<lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned int> > > >).
Make sure your type is registered with CEREAL_REGISTER_TYPE and that the archive you are using was included (and registered with CEREAL_REGISTER_ARCHIVE) prior to calling CEREAL_REGISTER_TYPE.
If your type is already registered and you still see this error, you may need to use CEREAL_REGISTER_DYNAMIC_INIT.

**Comment by yspolyakov** [comment]
Could you confirm you included all header files that are included at the beginning of "simple-real-numbers-serial.cpp"? The error typically implies that some of the serialization header files were not included. If this does not help, could you post the code here?

**Comment by sofianeazogagh** [comment]
Indeed, it is the header file "key/key-ser.h" that was missed. Thank you
