### ISSUE TITLE
Question: regarding to EvalKeySwitchPrecomputeCore, why it only times QHatInvModq to break digits?

### ISSUE THREAD

**Issue by helenpeng168** [openfheorg/openfhe-development#190]
I am reading the [digits breaking function](https://github.com/openfheorg/openfhe-development/blob/main/src/pke/lib/keyswitch/keyswitch-hybrid.cpp#L463). why it only times QHatInvModq?

let me give a simple example. if the radix set is 3,5,7,11, and the number to represent is 2257. 
The third digit should be `(2257-2257%(3*5)) / (3*5) mod 7`.

but it above code seems only times QHatInvModq `1/(3*5) mod 7`. where is the left part `-2257%(3*5)`?

**Comment by yspolyakov** [comment]
Issues are used to document requests, bugs, and other issues requiring code changes. For questions, we use the Discourse forum: https://openfhe.discourse.group/ Please ask your question there. Thank you.

**Comment by helenpeng168** [comment]
Got it. Thanks.
