### ISSUE TITLE
Fail to build with Intel HEXL backend

### ISSUE THREAD

**Issue by ajgappmark** [openfheorg/openfhe-development#205]
Hi,
I am trying to build openfhe with Intel HEXL backend by turning the following option ON through `ccmake`
```
WITH_INTEL_HEXL=ON
```
However, with the cmake fails to configure and reports the following error:
```
CMake Error at CMakeLists.txt:538 (include):
   include could not find requested file:

     third-party/intel-hexl/intel-hexl.cmake
```

I have tried to look into the history of repository to find presence of `third-party/intel-hexl/intel-hexl.cmake` but didn't find one either.

Could you please fix this issue? Has hexl backend was ever properly integrated into openfhe??

Thanks

**Comment by jbates-duality** [comment]
Good day.

Sorry for the delay in responding to this.

We have restructured the HEXL build to be coordinated by the openfhe-configurator repository, located here:

https://github.com/openfheorg/openfhe-configurator

The README.MD file in this repository contains build directions.

For future support concerns, please use the openfhe discourse forum located here:

https://openfhe.discourse.group/

This forum is monitored more closely, and has several OpenFHE developers actively fielding questions.

I hope this helps.

Thank you!

Jack Bates
Duality
