### ISSUE TITLE
dose openfhe support comparing two encrypted number?

### ISSUE THREAD

**Issue by Molamola1789** [openfheorg/openfhe-development#231]
is there a function that can do comparison?

**Comment by iquah1** [comment]
Can you open this question in https://openfhe.discourse.group/ ? In the future we're hoping to direct all questions about use of the library and FHE questions to that site. After you've posted your question there I'll follow up by coming back here, pasting the link in a comment and closing this issue. Thanks!

**Comment by iquah1** [comment]
Thank you! Closing and redirecting people to [OpenFHE Discourse: Does OpenFHE support comparison?](https://openfhe.discourse.group/t/does-openfhe-support-comparison/228)
