### ISSUE TITLE
Doc cleanup for binfhe deprecated header files. 

### ISSUE THREAD

**Issue by davidbrucecousins** [openfheorg/openfhe-development#233]
The following header files are gone now:
```
- src/binfhe/include/ringcore.h
- src/binfhe/include/lwecore.h
```
but are still referenced in `src/binfhe\include\README.md` and https://github.com/openfheorg/openfhe-development/blob/5fc1a84cad234ffdea547db03985d888ff943ad1/docs/sphinx_rsts/modules/binfhe.rst#L52

**Comment by yspolyakov** [comment]
Fixed in Commits https://github.com/openfheorg/openfhe-development/commit/5be8fc9be9c38569a746bf683ae103ca1a3b52cc and https://github.com/openfheorg/openfhe-development/commit/0f58aaafbe0cefd59575b7e67af523615a81877b
