### ISSUE TITLE
Add public/secret key pair to binFHE

### ISSUE THREAD

**Issue by davidbrucecousins** [openfheorg/openfhe-development#235]
Please add the capability for using a public/private keypair to `binFHE`.
It is an important capability that will *greatly* increase the application space within which we can use this scheme.

**Comment by sararv22** [comment]
New functions added : KeyGenTriple, EncryptN, Encryptn in lwe-pke.h, .cpp and binfhecontext.h, cpp

The KeyGenTriple generates a secret key skN and a corresponding public key pk with modulus Q and dimension N. It also generates a secret key skn with ring dimension n and a key switching key ksk to switch from skN to skn. Larger values of modulus and ring dimension Q and N for the public key encryption are used as opposed to q and n in secret key encryption to handle the higher noise levels with public key encryption. 
Encryption has two functions:
- EncryptN that encrypts a plaintext message m with public key pk and outputs a ciphertext of modulus Q and dimension N 
and 
- Encryptn that takes as input a ciphertext from EncryptN and does a sequence of modulus switching (to qKS), key switching (skN to skn) and modulus switching to q.

* Examples (excluding eval-sign and eval-decomp that works on large precision) are in binfhe/examples/pke folder.
* Updated benchmarks with timing for keygen and encrypt in existing binfhe-ap, binfhe-ginx and the pke version binfhe-ap-pke, binfhe-ginx-pke.
* Need to identify unittests to add for pke.

**Comment by sararv22** [comment]
Modified the code to use key switching key from BTKeyGen for public key encryption and removed the KeyGenTriple function. The following are the new functions added:
- KeyGenPair - generates a public, private key pair of modulus Q and dimension N

- PubKeyGen - generates a public key for a given secret key of modulus Q and dimension N

The function BTKeyGen() has a publicKeyFlag now which if set to true, generates a public key along with the bootstrapping keys. The default value is false, in which case it doesn't generate a public key. Also added unit tests for FHEW pke.
