### ISSUE TITLE
Segmentation Fault in binFHE serial examples

### ISSUE THREAD

**Issue by kvgarimella** [openfheorg/openfhe-development#239]
A segmentation fault occurs for the serialization examples for binFHE. Example:
```
$ ./build/bin/examples/binfhe/boolean-serial-binary
Generating keys.
Done generating all keys.
The cryptocontext has been serialized.
The refreshing key has been serialized.
The key switching key has been serialized.
The secret key sk1 key been serialized.
A ciphertext has been serialized.
The cryptocontext has been deserialized.
The refresh key has been deserialized.
The switching key has been deserialized.
The secret key has been deserialized.
The ciphertext has been deserialized.
Segmentation fault (core dumped)
```

OS: Ubuntu 20.04.4 LTS
Installation Process: https://openfhe-development.readthedocs.io/en/latest/sphinx_rsts/intro/installation/linux.html

**Comment by yspolyakov** [comment]
The bug affects serialization for any `binfhe` scenario. The serialization unit tests were not capturing this use case.

@dsuponitskiy Please fix the bug and add `Encrypt` and `EvalBinGate` to the binfhe serialization unit tests.
