### ISSUE TITLE
Is `autoconf` needed?

### ISSUE THREAD

**Issue by yspolyakov** [openfheorg/openfhe-development#251]
Installation instructions list `autoconf` as a system pre-requisite, e.g., https://openfhe-development.readthedocs.io/en/latest/sphinx_rsts/intro/installation/linux.html

Is `autoconf` still needed?

**Comment by dsuponitskiy** [comment]
From https://gmplib.org/manual/Installing-GMP: "GMP has an autoconf/automake/libtool based configuration system."
NTL requires autoconf/automake/libtool too.
