### ISSUE TITLE
Compilation problems with clang-11 and clang-14 

### ISSUE THREAD

**Issue by rscmendes** [openfheorg/openfhe-development#263]
Hello.
Would it be possible to add the supported compiler versions (or a list of tested builds)? In Ubuntu 22.04, the default and minimum clang version in the default repos is clang-14 and clang-11, respectively, while current instructions suggest clang-9.
Clang-14 and clang-11 compile OpenFHE, but result in errors when compiling the examples (if I didn't mess up any step).
With gcc-9 and g++-9 everything works fine -- all tests passed.
Thank you

**Comment by dsuponitskiy** [comment]
@rscmendes I have linked OpenFHE with clang-11 and clang-14 on Ubuntu 22.04 and successfully run unit tests. No any error. Could you be more specific and tell what you did exactly, step by step, so I can replicate this problem?

**Comment by rscmendes** [comment]
I am now on holidays, so I can't recreate -- I wonder if I did something wrong. But I remember not being able to compile the example [simple-real-numbers.cpp](https://github.com/openfheorg/openfhe-development/blob/main/src/pke/examples/simple-real-numbers.cpp). The error was something related with the use of a template and the error message mentioned C++ 17. Would you mind trying to compile and run this example? I will try it again with a fresh install when I come back. Thank you
