### ISSUE TITLE
Should we make CMAKE exit when building with emscripten on 128 bits?

### ISSUE THREAD

**Issue by iquah1** [openfheorg/openfhe-development#277]
TL;DR The description in the README and actual behavior do not line up

See [message(SEND_ERROR "NATIVE_SIZE == 128 is not supported for EMSCRIPTEN")](https://github.com/openfheorg/openfhe-development/blob/main/CMakeLists.txt#L291)

**Motivation**

I had 128-bit set and when I built the emscripten as per [palisade-wasm](https://gitlab.com/palisade/palisade-wasm/-/blob/master/README.md?plain=1#L54) I didn't actually error out.

**Comment by dsuponitskiy** [comment]
This was fixed for https://github.com/openfheorg/openfhe-development/pull/240
