### ISSUE TITLE
How to perform arithmetic on keys

### ISSUE THREAD

**Issue by tremblerz** [openfheorg/openfhe-development#279]
I am new to this library (and HE generally) and was wondering how to take two secret keys and use their difference as a new secret key for decryption. I am using `<DCRTPoly>`. I guess direct operator overloading does not make sense but is there a functionality I can use for performing arithmetic?

Here is a trimmed-down version of what I am trying to achieve -

```
    CryptoContext<DCRTPoly> c = GenCryptoContext(parameters);
    c->Enable(PKE);
    KeyPair<DCRTPoly> kp = c->KeyGen();
    PrivateKey<DCRTPoly> s = kp.secretKey;

    CryptoContext<DCRTPoly> c0 = GenCryptoContext(parameters);
    c0->Enable(PKE);
    KeyPair<DCRTPoly> kp0 = c0->KeyGen();
    PrivateKey<DCRTPoly> s0 = kp0.secretKey;

    // Initialize a private key as the difference between the two private keys
    PrivateKey<DCRTPoly> s1 = s - s0; // The kind of functionality I need.
```

Thanks for your help in resolving this.

**Comment by yspolyakov** [comment]
Please ask the question in the OpenFHE discourse forum at https://openfhe.discourse.group/
