### ISSUE TITLE
Bug in simple-integers-serial-bgvrns.cpp?

### ISSUE THREAD

**Issue by ntmarti** [openfheorg/openfhe-development#288]
When compiling I get the following error:

`Undefined symbols for architecture arm64:
  "lbcrypto::PseudoRandomNumberGenerator::m_prng", referenced from:
      lbcrypto::PseudoRandomNumberGenerator::GetPRNG() in debug-3de9f8.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

The error is related to deserializing the private key on line 274. This again refers to the `privatekey.h` on line 64 in the function `GenerateUniqueKeyID()`.

I am running the program on an Apple M1 processor. Apparently, the code should work on an Intel CPU.

**Comment by dsuponitskiy** [comment]
I has been able to link OpenFHE (the main branch) on macOS Ventura 13.1, Apple M1 Max, clang 14 without any compiler or link error.

**Comment by dsuponitskiy** [comment]
@ntmarti Please let us know if you still get this error and provide more details about your environment.

**Comment by simonfoldvik** [comment]
@dsuponitskiy The error is resolved. We are building an application on top of OpenFHE and have created our own build system, i.e., not using your provided `CMakeLists.User.txt`. Hence the error was not inside the build system you provide.

The resolution was to include linkage against OpenMP and adding the compiler flags `-Xpreprocessor -fopenmp`.

**Comment by simonfoldvik** [comment]
@dsuponitskiy The error is resolved. The resolution was to include linkage against OpenMP and adding the compiler flags `-Xpreprocessor -fopenmp`. This was inside our custom build system, not the one you provide through `CMakeLists.User.txt`.
