### ISSUE TITLE
LPCryptoParametersCKKS not found in src/pke/examples/advanced-real-numbers.cpp

### ISSUE THREAD

**Issue by kumarm17** [openfheorg/openfhe-development#293]
Hi openFHE teams, 
Thanks for creating one of the best FHE library. 
Here I have one question as below:

```
conts auto cryptoParamsCKKS =
    std::dynamic_pointer_cast<LPCryptoParametersCKKS<DCRTPoly>>(
        cc->GetCryptoParameters());

std::cout << fixed;
std::cout.precision(2);
// We have designed FLEXIBLEAUTO so that ciphertexts of a
// given level have a specific scaling factor.
std::cout << "\nScaling factors of levels: " << std::endl;
for (uint32_t i = 0; i < multDepth; i++) {
  std::cout << "Level " << i << ": "
            << cryptoParamsCKKS->GetScalingFactorOfLevel(i) << std::endl;
}
```

This is the commented code in /openfhe-development/src/pke/examples/advanced-real-numbers.cpp  and suggested to uncomment and run to observe the changes in scaling factors and depths.
But IDE does not found LPCryptoParametersCKKS, fixed, multDepth.

**Comment by yspolyakov** [comment]
This has been fixed in the `dev` branch. Closing the issue.
