### ISSUE TITLE
Question regarding the rotation in BFV

### ISSUE THREAD

**Issue by Qi-Pang** [openfheorg/openfhe-development#307]
Suppose we have a ciphertext with 8192 slots encrypted using BFV, e.g., `C = Enc([1, 2, 3, 4, ..., 8192])`.

Then we rotate this ciphertext for 1 step and get `C' = EvalRotate(C, 1)`.

I wanted to get `C' = Enc([8192, 1, 2, 3, 4, ..., 8191])` but I noticed that the result is rotated in "2 batches": 
`C' = Enc([4096, 1, 2, 3, 4, ..., 4095,   8192, 4097, 4098, 4099, ..., 8191])`. 
That is, both the first and the second half of `C` are rotated by one step.

Is it possible to disable this feature and just rotate the whole ciphertext by one step? Or can I change the "batch number" and get `C' = Enc([128, 1, 2, 3, ..., 127,   256, 129, 130, ..., 255, ...])`?

**Comment by yspolyakov** [comment]
Please ask this question in the OpenFHE discourse forum at https://openfhe.discourse.group/, the main area for OpenFHE discussions. We use issues to track bugs/feature requests/etc.
