### ISSUE TITLE
Create a function with better estimation of levels consumed in bootstrapping

### ISSUE THREAD

**Issue by sarojaduality** [openfheorg/openfhe-development#313]
The GetBootstrapDepth function requires an approximateBootstrapDepth parameter. We can improve this function by examining EvalBootstrap to see how many ModReduce calls we make.

**Comment by yspolyakov** [comment]
* `GetBootstrapDepth` should not take apprixModDepth as an argument. 
* Determine the depth for a given vector of coefficients using the  table described in https://github.com/openfheorg/openfhe-development/blob/dev/src/pke/examples/FUNCTION_EVALUATION.md Add the table to `ckks-utils.cpp`
* Change the hard-coded value of 8 in `GetBootstrapDepth` to use this new mechanism
