### ISSUE TITLE
Where is config_core.h?

### ISSUE THREAD

**Issue by harichards** [openfheorg/openfhe-development#324]
Compilation fails with `fatal error: config_core.h: No such file or directory`. The documentations says the following:

> As of release 1.10.0, `src/core/config_core.h` is used to control the build of the core component, and any library code that depends on it. Future developments will expand this to other components.

However, this release does not even exist (the latest is 1.0.2) and the file is nowhere to be found.

**Comment by harichards** [comment]
Looks like the issue is with these four lines in CMakeLists.txt:
```cmake
include_directories( ${CMAKE_SOURCE_DIR}/third-party/google-test/googletest )
include_directories( ${CMAKE_SOURCE_DIR}/third-party/google-test/googletest/include )
include_directories( ${CMAKE_SOURCE_DIR}/src/core/include )
include_directories( ${CMAKE_BINARY_DIR}/src/core )
```
Should be using `${CMAKE_CURRENT_*_DIR}` as opposed to `${CMAKE_*_DIR}` because `${CMAKE_*_DIR}` does not always refer to the root of your repository.

**Comment by dsuponitskiy** [comment]
@harichards Thank you for submitting this issue. 
Re: your changes to src/pke/CMakeLists.txt.
What feature is this going to provide to the library? Is this required for using CMAKE_CURRENT_*?

**Comment by dsuponitskiy** [comment]
@harichards 
Re: your changes to src/pke/CMakeLists.txt.
What feature is this going to provide to the library? Is this required for using CMAKE_CURRENT_*?

Also, could you provide more information about how you built OpenFHE: environment, compiler, OS, etc?
