### ISSUE TITLE
Exception message in bootstrapping

### ISSUE THREAD

**Issue by sarojaduality** [openfheorg/openfhe-development#351]
We throw an exception that says
`
[…]/dcrtpoly.cpp:385 DCRTPolyImpl’s towers are not initialized.
`
when we try to bootstrap with 0 levels left. We should have a more descriptive error message.

**Comment by caesaretos** [comment]
Issue [355](https://github.com/openfheorg/openfhe-development/issues/355) will resolve this issue as well. No additional work is required.
