### ISSUE TITLE
bootstrapping AutomorphismKey keys is Exceeded maximum protobuf size of 2GB

### ISSUE THREAD

**Issue by 604254229** [openfheorg/openfhe-development#360]

**Comment by yspolyakov** [comment]
@604254229 Could you provide more information about the bug? What environment are you using? What computation are performing? What code are you running? Basically all the information that is needed to recreate the issue.

**Comment by 604254229** [comment]
I am using Protobuf messages to store and transmit AutomorphismKey over the network, but when EvalBootstrapKeyGen is called, the size of AutomorphismKey grows significantly and exceeds the Protobuf serialization size limit. I would like to ask if there are any plans to optimize and reduce the size of the BootstrapKey in the OpenFHE project, or if there are any other suggestions for using bootstrapping serialization functionality

**Comment by yspolyakov** [comment]
I've created a topic for this: https://openfhe.discourse.group/t/bootstrapping-automorphismkey-keys-exceeds-maximum-protobuf-size-of-2gb/505/2 We use issues only for bugs, enhancements. The discourse forum is for discussions. I am closing this issue. Please reply in the forum instead. Thanks.
