### ISSUE TITLE
Openfhe_error failed to catch an not_available_error while attempting to call EvalRotate() on an uninitialized index

### ISSUE THREAD

**Issue by ailanxier** [openfheorg/openfhe-development#362]
Reproduce it with the [simple-real-numbers example](https://github.com/openfheorg/openfhe-development/blob/main/src/pke/examples/simple-real-numbers.cpp).
```cpp
cc->EvalRotateKeyGen(keys.secretKey, {1, -2});
```
When changing the second parameter from `{1,-2}` to `{1}`, calling `EvalRotate(c1, -2)` results in a std::out_of_range exception.
```bash
CKKS scheme is using ring dimension 16384

Input x1: (0.25, 0.5, 0.75, 1, 2, 3, 4, 5,  ... ); Estimated precision: 50 bits

Input x2: (5, 4, 3, 2, 1, 0.75, 0.5, 0.25,  ... ); Estimated precision: 50 bits

terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
[1]    494120 IOT instruction  ./bin/simple-real-numbers
```
After reading the source code, I found that in the function `EvalAutomorphism()` located in the [base-leveledshe.cpp](https://github.com/openfheorg/openfhe-development/blob/122f470e0dbf94688051ab852131ccc5d26be934/src/pke/lib/schemebase/base-leveledshe.cpp#L416), there is no check to verify if the key `i` exists in the `evalKeyMap`. This leads to the exception when calling `evalKeyMap.at(i)`. By adding the following code before calling `evalKeyMap.at(i)`, this exception can be caught by `openfhe_error`, and maybe more meaningful exception information can be provided.
```cpp
    //  verify if the key i exists in the evalKeyMap
    if(evalKeyMap.find(i) == evalKeyMap.end())
        OPENFHE_THROW(not_available_error, "...exception information about the unset index...");
```

**Comment by dsuponitskiy** [comment]
A fix is currently available in the dev branch of OpenFHE. We will move it to main with the next OpenFHE release
