### ISSUE TITLE
Some problems about threshold-fhe and whether can serialize parameters

### ISSUE THREAD

**Issue by hui09-m** [openfheorg/openfhe-development#375]
Well, I want to make threshold-fhe be serialized, so I test it simply just as following description, I change code on 'threshold-fhe.cpp' to do the test.
1.make three cryotocontext as client1, client2 and server use the same parameters like this:
```
CryptoContext<DCRTPoly> cc = GenCryptoContext(parameters);
CryptoContext<DCRTPoly> cc2 = GenCryptoContext(parameters);
CryptoContext<DCRTPoly> ccs = GenCryptoContext(parameters);
```

2.use their own cryptocontext to generate keypair、multkey、sumkey and then encrypt message. 
```
ciphertext1 = cc1->Encrypt(kp2.publicKey, plaintext1);
ciphertext2 = cc2->Encrypt(kp2.publicKey, plaintext2);
ciphertext3 = cc2->Encrypt(kp2.publicKey, plaintext3);
```

3.use 'ccs' to evaluate like this:
```
ciphertextAdd12  = ccs->EvalAdd(ciphertext1, ciphertext2);
ciphertextAdd123 = ccs->EvalAdd(ciphertextAdd12, ciphertext3);

auto ciphertextMultTemp = ccs->EvalMult(ciphertext1, ciphertext3);
auto ciphertextMult     = ccs->ModReduce(ciphertextMultTemp);
auto ciphertextEvalSum  = ccs->EvalSum(ciphertext3, batchSize);
```

4.ues 'cc' and 'cc2' to decrypt partial results like this:
```
auto ciphertextPartial1 = cc->MultipartyDecryptLead({ciphertextAdd123}, kp1.secretKey);
auto ciphertextPartial2 = cc2->MultipartyDecryptMain({ciphertextAdd123}, kp2.secretKey);
```

However, I see the function `MultipartyDecryptLead()` and `MultipartyDecryptMain()` will check whether the ciphercontext mached cryptocontext, you see, I use 'ccs' to evaluate, why is it mached?  

It can run corectly, however when I serialize the cryptocontext to do, it shows error like this:
![image](https://user-images.githubusercontent.com/83063300/233893947-4efbe3b1-f811-4370-940a-235d01ac978b.png)
I don't know why? Can you give me explanation？For they use parameters to generate cryptocontext not just use cryptocontext itself?
I then try to serialize parameters use different type, it can't compile.
```
Serial::SerializeToFile(DATAFOLDER + parmsLocation, parameters, SerType::JSON);
Serial::SerializeToFile(DATAFOLDER + parmsLocation, parameters, SerType::BINARY);
```
Is there method to serialize parameters?

**Comment by yspolyakov** [comment]
Hi @hui09-m We use issues only for reporting bugs, requesting enhancements, etc. We use the OpenFHE discourse forum for questions and discussions: https://openfhe.discourse.group/ Please ask your question there.
