### ISSUE TITLE
Setting Lower MultiplicativeDepth, FirstModSize or BatchSize Results in Incorrect EvalMult Output

### ISSUE THREAD

**Issue by ailanxier** [openfheorg/openfhe-development#376]
I used the following code which led to incorrect results, and tested it with several scenarios.

- Setting a higher `MultiplicativeDepth` value, such as `2`, produces correct result
- Using the default value of `FirstModSize`, by commenting out the `SetFirstModSize()` line, produces correct result.
- Using the default value of `BatchSize`, by commenting out the `SetBatchSize()` line, produces correct result.
- Using `EvalLinearWSum()` leads to same wrong result.

The error was found in a complex computing scenario and was reduced to this section of code. Despite the output's high `Estimated precision` value, it is evident that the results are incorrect and therefore misleading. 
```cpp
int main() {
    CCParams<CryptoContextCKKSRNS> parameters;
    parameters.SetMultiplicativeDepth(1);
    parameters.SetScalingModSize(59);
    parameters.SetFirstModSize(50);
    parameters.SetBatchSize(8);
    CryptoContext<DCRTPoly> cc = GenCryptoContext(parameters);
    cc->Enable(PKE);
    cc->Enable(KEYSWITCH);
    cc->Enable(LEVELEDSHE);
    std::cout << "CKKS scheme is using ring dimension " << cc->GetRingDimension() << std::endl << std::endl;
    auto keys = cc->KeyGen();
    cc->EvalMultKeyGen(keys.secretKey);
    std::vector<double> x1 = {1};
    Plaintext ptxt1 = cc->MakeCKKSPackedPlaintext(x1);
    std::cout << "Input x1: " << ptxt1 << std::endl;
    auto c1 = cc->Encrypt(keys.publicKey, ptxt1);
    auto res_ctxt = cc->EvalMult(c1, 1);
    Plaintext result;
    std::cout.precision(8);
    std::cout << std::endl << "Results of EvalLinearWSum: " << std::endl;
    cc->Decrypt(keys.secretKey, res_ctxt, &result);
    result->SetLength(8);
    std::cout << "1*c1 = " << result << std::endl;
    return 0;
}

// result
CKKS scheme is using ring dimension 16384

Input x1: (1,  ... ); Estimated precision: 59 bits


Results of EvalLinearWSum: 
1*c1 = (0.0011247116, 0.00080010595, -0.0044353944, -0.0025511492, 0.002679197, 0.00095785407, 0.0034470322, -0.0020223553,  ... ); Estimated precision: 51 bits
```

**Comment by yspolyakov** [comment]
This scenario logically does not make sense. Scaling factor should not be higher than `FirstModSize`, at least for the example you tried. There could be some scenarios where this is possible, e.g., the user works with very small numbers (less than $10^{-3}$ for your settings). Either way, https://github.com/openfheorg/openfhe-development/issues/339 is related to this, and we will try to add exception handling for the scaling mod size wherever it makes sense.
