### ISSUE TITLE
How to use ， EvalMult to increase the ciphertext level and how to set the "level" parameter in MakeCKKSPackedPlaintext and the timing of calling EvalBootstrap?

### ISSUE THREAD

**Issue by 604254229** [openfheorg/openfhe-development#388]
Do you have sample code with a large multiplication depth combined with ckk_bootstrapping? In the examples I've seen, only MakeCKKSPackedPlaintext+EvalBootstrap functions are used. When I tried to use 12 layers of multiplication depth with EvalBootstrap, I got significant errors. When using boostrapping, how should I set the "level" parameter in MakeCKKSPackedPlaintext? For example, if the total depth is 28 and "levelsUsedBeforeBootstrap" is set to 8, and MakeCKKSPackedPlaintext starts from level 0, when should I perform EvalBootstrap? Will EvalBootstrap directly jump to layer 21?

For example, how to use CKK bootstrapping to implement a function and ensure accurate results?

<img width="551" alt="image2023-4-27_16-20-9" src="https://user-images.githubusercontent.com/13174126/236151914-f6fd614c-a66e-4417-b7de-2fb736e3dc02.png">

**Comment by iquah1** [comment]
We keep this repo for bug reports. For discussions please go to our [discourse page](https://openfhe.discourse.group/). We find that it makes it easier for users to search through discussions that way.

Thank you!
