### ISSUE TITLE
openfhe-development/src/pke/examples/advanced-ckks-bootstrapping.cpp  err

### ISSUE THREAD

**Issue by 604254229** [openfheorg/openfhe-development#390]
When I adjust the data size to between 1000-2000 and only perform EvalBootstrap, the result is completely incorrect.
<img width="383" alt="企业微信截图_16832568435368" src="https://user-images.githubusercontent.com/13174126/236371204-c6558bd8-98ab-4791-8ba9-cde33df685e0.png">

<img width="707" alt="企业微信截图_16832568627805" src="https://user-images.githubusercontent.com/13174126/236371247-2d6dbb77-581d-443e-a9dc-c41899f0c260.png">

**Comment by yspolyakov** [comment]
See https://openfhe.discourse.group/t/questions-on-ckks-bootstrapping-with-some-computations-after-bootstrapping/535/7 This behavior is expected. Please read the discourse forum thread for details.
