### ISSUE TITLE
Test for BFVrns_INNERPRODUCT failed in the dev branch

### ISSUE THREAD

**Issue by dsuponitskiy** [openfheorg/openfhe-development#396]
[ RUN      ] UTBFVRNS_INNERPRODUCT.Test_BFVrns_INNERPRODUCT
/home/dima/Git/openfhe-development/src/pke/unittest/utbfvrns/UnitTestBFVrnsInnerProduct.cpp:108: Failure
Expected equality of these values:
  innerProductHE
    Which is: 3649
  expectedResult
    Which is: 55
[  FAILED  ] UTBFVRNS_INNERPRODUCT.Test_BFVrns_INNERPRODUCT (57 ms)

**Comment by dsuponitskiy** [comment]
I have run it multiple times and the value of innerProductHE is different every time:
./unittest/pke_tests --gtest_filter=*UTBFVRNS_INNERPRODUCT.Test_BFVrns_INNERPRODUCT*

**Comment by iquah1** [comment]
Sorry, you'll need to rope someone who has more FHE knowledge into this. I'm not sure why it's failing there :(

**Comment by dsuponitskiy** [comment]
This was caused by https://github.com/openfheorg/openfhe-development/pull/391
