### ISSUE TITLE
 No such file or directory    57 | #include "cereal/cereal.hpp"

### ISSUE THREAD

**Issue by zzzhhhlll** [openfheorg/openfhe-development#409]
F:/openfhe-development-main/src/core/include/utils/serializable.h:57:10: fatal error: cereal/cereal.hpp: No such file or directory
   57 | #include "cereal/cereal.hpp"

**Comment by takashimayunachikage** [comment]
I've encountered the same problem. How did you solve it?

**Comment by pavan-ranganath** [comment]
I have encountered same issue with 1.2.0. Any idea how to fix it ?

`
/src/core/include/utils/serializable.h:60:10: fatal error: cereal/cereal.hpp: No such file or directory
   60 | #include "cereal/cereal.hpp"
      |          ^~~~~~~~~~~~~~~~~~~
`
