### ISSUE TITLE
Choosing scaleFactorBits and FirstModSize for Chebyshev Polynomial Evaluation

### ISSUE THREAD

**Issue by kumarm17** [openfheorg/openfhe-development#423]
I'm facing an issue with evaluating a Chebyshev polynomial whose coefficients are `{0.0000, 6.4594, 0.0000, -49.7848, 0.0000, 234.2367, 0.0000, -618.7302, 0.0000, 945.7100, 0.0000, -830.6212, 0.0000, 388.9068, 0.0000, -75.1798}`.

I've tried adjusting the scaleFactorBits and FirstModSize parameters to achieve accurate results. In the SEAL library, setting scaleFactorBits to 35 and FirstModSize to 45 worked fine (more precisely q_i moduli in SEAL are {45, 35, 35, 35, 35, 35, 35, 35, 35, 45}). However, when attempting the same in openFHE with scaleFactorBits ranging from 40 to 59 bits and FirstModSize of 60, the results were incorrect.

I have also tested both my implementation of EvalPoly and the openFHE library's EvalPoly function, but encountered the same error. The input range for x in this Chebyshev polynomial is [-1, 1].

I would appreciate guidance or insights on correctly evaluating this Chebyshev polynomial in openFHE, as well as any suggestions on the appropriate parameter settings to achieve accurate results.

Thank you for your assistance!

**Comment by yspolyakov** [comment]
Please ask the question at the OpenFHE discourse forum: https://openfhe.discourse.group/ We use github issue for reporting bugs, documenting enhancements, etc.
