### ISSUE TITLE
Bootstrapping modulus not set correctly in overload of GenerateBinFHEContext

### ISSUE THREAD

**Issue by andreea-alexandru** [openfheorg/openfhe-development#426]
PreviousPrime<NativeInteger>(FirstPrime<NativeInteger>(logQprime, ringDim), ringDim) ->
PreviousPrime<NativeInteger>(FirstPrime<NativeInteger>(logQprime, 2*ringDim), 2*ringDim).

However, for the two allowed values of logQprime, the generated modulus is correctly satisfying 1 mod 2*ringDim.

**Comment by dsuponitskiy** [comment]
Added a link between this issue and the PR opened for it.
