### ISSUE TITLE
Threshold FHE deserialization issues

### ISSUE THREAD

**Issue by devharsh** [openfheorg/openfhe-development#431]
I am trying to save keys to files and read from them for threshold CKKS based on the following examples
- src/pke/examples/simple-real-numbers-serial.cpp
- src/pke/examples/threshold-fhe-5p.cpp

While I could successfully save and read CC, PK, and SK for (single-key) CKKS, I am having issues while loading keys in a threshold (multi-key) setting.

**Comment by yspolyakov** [comment]
@devharsh Please use the OpenFHE discourse forum to ask questions. We use issues only for tracking bugs and enhancement requests. See https://openfhe.discourse.group/t/keyswitch-key-serialization/579 It might be relevant. Also, posting a specific example would be helpful.
