### ISSUE TITLE
Max64BitValue

### ISSUE THREAD

**Issue by enum-class** [openfheorg/openfhe-development#445]
I have a question about [Max64BitValue](https://github.com/openfheorg/openfhe-development/blob/f4baaa449e0828bdd272b59d170c66f4d64d79ed/src/core/include/utils/utilities.h#L146) method. 
does it return The biggest/largest integer that can be stored in a double without losing precision ?

**Comment by enum-class** [comment]
what is the point of (2^10-1)

**Comment by yspolyakov** [comment]
Please use the discourse forum for questions: https://openfhe.discourse.group/
