### ISSUE TITLE
Error while installation on Linux

### ISSUE THREAD

**Issue by golfus06** [openfheorg/openfhe-development#448]
while running the make command i am getting error
project@project-virtual-machine:~/openfhe-development/build$ make
-- demoData folder already exists
[  0%] Built target third-party
[  0%] Building CXX object src/core/CMakeFiles/coreobj.dir/lib/lattice/be2-poly-impl.cpp.o
In file included from /home/project/openfhe-development/src/core/lib/lattice/be2-poly-impl.cpp:36:
In file included from /home/project/openfhe-development/src/core/include/lattice/lat-hal.h:42:
In file included from /home/project/openfhe-development/src/core/include/lattice/hal/default/lat-backend-default.h:39:
In file included from /home/project/openfhe-development/src/core/include/lattice/hal/default/dcrtpoly.h:45:
In file included from /home/project/openfhe-development/src/core/include/math/hal.h:53:
/home/project/openfhe-development/src/core/include/utils/serializable.h:60:10: fatal error: 'cereal/cereal.hpp' file not found
#include "cereal/cereal.hpp"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/core/CMakeFiles/coreobj.dir/build.make:76: src/core/CMakeFiles/coreobj.dir/lib/lattice/be2-poly-impl.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:561: src/core/CMakeFiles/coreobj.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by dsuponitskiy** [comment]
@golfus06 I was not able to replicate the error on Ubuntu 22.04 with g++-11. In order to investigate could you provide answers to the following questions:
1. If you followed the installation and link  instructions on this page https://openfhe-development.readthedocs.io/en/latest/sphinx_rsts/intro/installation/linux.html
2. What the Linux distro and the compiler were used and their versions.

**Comment by dsuponitskiy** [comment]
@golfus06 Let me know if you are still experiencing this issue.
You may also be able to find some answers by searching the OpenFHE forum at https://openfhe.discourse.group/. We encourage OpenFHE users to post their questions there.
