### ISSUE TITLE
Conflict with third-party libraries

### ISSUE THREAD

**Issue by yasha-shampur** [openfheorg/openfhe-development#473]
In the file [debug.h](https://github.com/openfheorg/openfhe-development/blob/a7415334b8fc033501809d9547be92fb90228c0a/src/core/include/utils/debug.h#L201)
there is the macros 
`#define duration(a)    std::chrono::duration_cast<std::chrono::milliseconds>(a).count()`. 
debug.h file is included through utils.h to openfhe.h. The macros is defined in global namespace which is the reason for some issues with other libraries. 
For example, I faced a problem with [mongo-cxx-driver](https://github.com/mongodb/mongo-cxx-driver), because inside driver there is line: 
```
    ///
    /// Returns the duration of the failed operation.
    ///
    /// @return The duration in microseconds.
    ///
    std::int64_t duration() const;
```
When ypu use openfhe.h and mongo driver files, you faced an issue, like this: 

```
/usr/local/include/mongocxx/v_noabi/mongocxx/events/heartbeat_succeeded_event.hpp:55:18: error: non-friend class member 'duration_cast' cannot have a qualified name
    std::int64_t duration() const;
                 ^~~~~~~~~~
/usr/local/include/openfhe/core/utils/debug.h:201:37: note: expanded from macro 'duration'
#define duration(a)    std::chrono::duration_cast<std::chrono::milliseconds>(a).count()
```

**Comment by yspolyakov** [comment]
Please post the question in the OpenFHE discourse forum at https://openfhe.discourse.group/ We use github issues only for documenting confirmed bugs and feature requests.
