### ISSUE TITLE
Multiparty decryption error

### ISSUE THREAD

**Issue by yinyanshuai** [openfheorg/openfhe-development#529]
I found that when I split the three party threshold multi key homomorphic sample code into three files for collaborative calculation, multiplication decryption would cause errors due to large approximation errors. I output some of the intermediate parameters and found that the logstd was too high, and the Element<Poly>was also significantly different from normal decryption. I'm not sure if there was a problem with my code flow. Could you please help me check it.
[resources.zip](https://github.com/openfheorg/openfhe-development/files/12252536/resources.zip)

**Comment by yspolyakov** [comment]
I suggest posting this at https://openfhe.discourse.group/ We create issues only for confirmed bugs. Thank you!
