### ISSUE TITLE
decryption is failed

### ISSUE THREAD

**Issue by macknight** [openfheorg/openfhe-development#559]
Hi, 
When I use openfhe-python and customized code based on openfhe-development, the ciphertexts can be generated successfully, but the decryption process has error below. Any ideas?

**terminate called after throwing an instance of 'lbcrypto::deserialize_error'
  what():  /usr/local/include/openfhe/core/math/hal/bigintdyn/ubintdyn.h:910 serialized object version 257 is from a later version of the library**

BR

**Comment by dsuponitskiy** [comment]
Could you provide the code of your application for further investigation?

**Comment by yspolyakov** [comment]
Please post this question at https://openfhe.discourse.group/ I also want to ask several clarifying questions once the post is created. Thanks.
