### ISSUE TITLE
Multiplications failing after bootstrapping

### ISSUE THREAD

**Issue by imtiyazuddin** [openfheorg/openfhe-development#564]
I tried to do some multiplications after bootstrapping was done, but it keeps giving this error (even though it shows levels rem is 10 after bootstrapping):

CKKS scheme is using ring dimension 4096

Input: (2, 2, 2, 2, 2, 2, 2, 2,  ... ); Estimated precision: 59 bits

Initial number of levels remaining: 1
Number of levels remaining after bootstrapping: 10

terminate called after throwing an instance of 'lbcrypto::math_error'
  what():  /home/imtiyazuddin/Ubuntu/openfhe-development/src/pke/lib/encoding/ckkspackedencoding.cpp:537 The decryption failed because the approximation error is too high. Check the parameters. 
Aborted (core dumped)

why is this?

**Comment by dsuponitskiy** [comment]
You may be able to find some answers by searching [the OpenFHE forum](https://openfhe.discourse.group/). We encourage OpenFHE users to post their questions there.
