### ISSUE TITLE
Segmentation Fault in Matrix<DCRTPoly> SetFormat

### ISSUE THREAD

**Issue by TianWZhang** [openfheorg/openfhe-development#635]
Hello,

I wrote some examples with openFHE on my system. However, I am getting a Segmentation Fault once the actual computation of generating discrete uniform matrix begins. I have found out the cause of the error to be the call of `Matrix<DCRTPoly>::SetFormat` function. 

```c++
Matrix<DCRTPoly> Context::GenDiscreteUniformMatrix(usint rows, usint columns) const {
  auto zero_alloc = DCRTPoly::Allocator(params_, Format::EVALUATION);
  auto uniform_alloc = DCRTPoly::MakeDiscreteUniformAllocator(params_, Format::COEFFICIENT);
  Matrix<DCRTPoly> res(zero_alloc, rows, columns, uniform_alloc);
  res.SetFormat(Format::EVALUATION);
  return res;
}
```
Here is the output of running the above function:
```
Segmentation fault (core dumped)
```

Here is the definition of `void Matrix<Element>::SetFormat(Format format) ` in openfhe library(`matrix-lattice-impl.h`).
```c++
template <typename Element>
void Matrix<Element>::SetFormat(Format format) {
    if (rows == 1) {
#pragma omp parallel for num_threads(OpenFHEParallelControls.GetThreadLimit(cols))
        for (size_t col = 0; col < cols; ++col) {
            data[0][col].SetFormat(format);
        }
    }
    else {
#pragma omp parallel for num_threads(OpenFHEParallelControls.GetThreadLimit(rows))
        for (size_t row = 0; row < rows; ++row) {
            for (size_t col = 0; col < cols; ++col) {
                data[row][col].SetFormat(format);
            }
        }
    }
}
```

After deleting the above omp parallel codes, the Segmentation Fault disappeared. I am wondering whether this error is related to how I call Matrix<DCRTPoly>::SetFormat`  function or is there a bug in the implementation of this function.
Any help would be appreciated! Thanks!

**Comment by pascoec** [comment]
Which OpenFHE version are you using?

The changes [here](https://github.com/openfheorg/openfhe-development/pull/599) should fix your issue. If possible, try rerunning your examples with v.1.1.2. Are you still getting a segmentation fault?
