### ISSUE TITLE
Building with Xcode / iOS

### ISSUE THREAD

**Issue by akolio** [openfheorg/openfhe-development#648]
Hi,

Do you have any pointers / ideas on how to build for Xcode, preferably with iOS targets and all relevant architectures?
 
I don't have any prior experience with cmake, but I tried the following.

1. Commented out unix makefiles generator in PreLoad.cmake
-set (CMAKE_GENERATOR "Unix Makefiles" CACHE INTERNAL "" FORCE)
+# set (CMAKE_GENERATOR "Unix Makefiles" CACHE INTERNAL "" FORCE)

2. Ran cmake in subdir with the Xcode generator
cmake .. -GXcode  

3. Opened the generated OpenFHE.xcodeproj in Xcode
4. Let Xcode Autocreate Schemes from the dialog:
"The project “OpenFHE” contains a large number of targets, which may cause a large number of schemes to be automatically created. If you prefer, you may instead manually create only the schemes you need."

5. Ran into a bunch of "Implicit conversion loses integer precision" warnings that Xcode treats as errors
6. Tried to disable warnings on implicit conversions to 32 bit types from the project's build settings, but it didn't seem to have any effect.

**Comment by yspolyakov** [comment]
Please ask your question at https://openfhe.discourse.group/
