### ISSUE TITLE
Encountered some problems when calling NTL library in OpenFHE

### ISSUE THREAD

**Issue by Cmiiii** [openfheorg/openfhe-development#649]
I want to call the NTL library in OpenFHE. I have successfully installed NTL, GMP, etc. locally, and set both BUILD_extras and WITH_NTL to ON in OpenFHE's cmakelists. However, I encountered some problems during make.

`/usr/bin/ld: CMakeFiles/prng.dir/examples/prng.cpp.o: in function `_ntl_enable_if<_ntl_is_char_pointer<char const*>::value, void>::type NTL::conv<NTL::ZZ, char const*>(NTL::ZZ&, char const*)':
prng.cpp:(.text._ZN3NTL4convINS_2ZZEPKcEEN14_ntl_enable_ifIXsr20_ntl_is_char_pointerIT0_E5valueEvE4typeERT_S6_[_ZN3NTL4convINS_2ZZEPKcEEN14_ntl_enable_ifIXsr20_ntl_is_char_pointerIT0_E5valueEvE4typeERT_S6_]+0x127): undefined reference to `NTL::operator>>(std::istream&, NTL::ZZ&)'
/usr/bin/ld: prng.cpp:(.text._ZN3NTL4convINS_2ZZEPKcEEN14_ntl_enable_ifIXsr20_ntl_is_char_pointerIT0_E5valueEvE4typeERT_S6_[_ZN3NTL4convINS_2ZZEPKcEEN14_ntl_enable_ifIXsr20_ntl_is_char_pointerIT0_E5valueEvE4typeERT_S6_]+0x141): undefined reference to `NTL::TerminalError(char const*)'
/usr/bin/ld: prng.cpp:(.text._ZN3NTL4convINS_2ZZEPKcEEN14_ntl_enable_ifIXsr20_ntl_is_char_pointerIT0_E5valueEvE4typeERT_S6_[_ZN3NTL4convINS_2ZZEPKcEEN14_ntl_enable_ifIXsr20_ntl_is_char_pointerIT0_E5valueEvE4typeERT_S6_]+0x1a8): undefined reference to `NTL::TerminalError(char const*)'
/usr/bin/ld: CMakeFiles/prng.dir/examples/prng.cpp.o: in function `main.cold':
prng.cpp:(.text.unlikely+0xb): undefined reference to `_ntl_gfree(_ntl_gbigint_body*)'
/usr/bin/ld: prng.cpp:(.text.unlikely+0x1a): undefined reference to `_ntl_gfree(_ntl_gbigint_body*)'
/usr/bin/ld: CMakeFiles/prng.dir/examples/prng.cpp.o: in function `main':
prng.cpp:(.text.startup+0x86): undefined reference to `_ntl_gcopy(_ntl_gbigint_body*, _ntl_gbigint_body**)'
/usr/bin/ld: prng.cpp:(.text.startup+0x95): undefined reference to `_ntl_gfree(_ntl_gbigint_body*)'
/usr/bin/ld: prng.cpp:(.text.startup+0xbe): undefined reference to `NTL::operator<<(std::ostream&, NTL::ZZ const&)'
/usr/bin/ld: prng.cpp:(.text.startup+0xd5): undefined reference to `_ntl_gfree(_ntl_gbigint_body*)'
/usr/bin/ld: prng.cpp:(.text.startup+0x10b): undefined reference to `_ntl_gfree(_ntl_gbigint_body*)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/pke/CMakeFiles/prng.dir/build.make:100：bin/examples/pke/prng] 错误 1
make[1]: *** [CMakeFiles/Makefile2:1339：src/pke/CMakeFiles/prng.dir/all] 错误 2
make: *** [Makefile:136：all] 错误 2`

**Comment by yspolyakov** [comment]
Please ask your question at https://openfhe.discourse.group/
