### ISSUE TITLE
`std::is_integral` has compiler/platform-dependent behavior for `__int128_t`

### ISSUE THREAD

**Issue by j2kun** [openfheorg/openfhe-development#669]
When compiling the example from https://github.com/openfheorg/openfhe-development/issues/667 with clang-17 with `-std=c++17`, I see 

```
external/openfhe/src/core/lib/math/hal/bigintfxd/ubintfxd.cpp:121:13: error: no matching function for call to 'GetMSB'
  121 |     m_MSB = lbcrypto::GetMSB(val);
      |             ^~~~~~~~~~~~~~~~
external/openfhe/src/core/include/math/nbtheory.h:167:24: note: candidate template ignored: requirement 'std::is_integral_v<unsigned __int128>' was not satisfied [with T = U128BITS]
  167 | inline constexpr usint GetMSB(T x) {
      |
```

After reading https://quuxplusone.github.io/blog/2019/02/28/is-int128-integral/ it seems this is intended behavior, but I wanted to surface it because the readme in the repository states

> OpenFHE supports any GNU C++ compiler version 9 or above and clang C++ compiler version 10 or above.

It would be nice to make the build succeed for both `-std=c++XX` and `-std=gnu++XX`, though I don't know enough to say what would be required to do that. I was able to get everything to compile with `-std=gnu++XX` for any `XX`

**Comment by yspolyakov** [comment]
@j2kun The fix has been merged to the dev branch, It will be merged to master as part of releasing v1.1.3.
