### ISSUE TITLE
Missing copy assignment operators on upgrading to 1.1.3

### ISSUE THREAD

**Issue by j2kun** [openfheorg/openfhe-development#701]
Somewhere between 1.0.0 and 1.1.3 BinFHEContext lost its copy assignment operator, which we use in https://github.com/google/fully-homomorphic-encryption during code generation.

Can this be restored, or an alternative approach be suggested? Using `std::move` also fails

```
fully_homomorphic_encryption/transpiler/data/primitives_openfhe.types.h:1136:9: 
error: object of type 'lbcrypto::BinFHEContext' cannot be assigned because
its copy assignment operator is implicitly deleted
 1136 |     cc_ = std::move(rhs.cc_); 
```

**Comment by dsuponitskiy** [comment]
The fix has been added to dev. It will be available in the main branch upon the next release
