### ISSUE TITLE
Exception is not being caught in `MakePackedPlaintext`

### ISSUE THREAD

**Issue by mdvillagra** [openfheorg/openfhe-development#727]
When the plaintext modulus and cyclotomic number do not satisfy the condition that $m$ divides $q-1$, there is an error 

> Please provide a primeModulus(q) and a cyclotomic number(m) satisfying the condition: (q-1)/m is an integer. 

and immediately the program aborts.

I don't know if the exception is being thrown correctly in [this line](https://github.com/openfheorg/openfhe-development/blob/94fd76a1d965cfde13f2a540d78ce64146fc2700/src/core/include/math/nbtheory-impl.h#L191), because the code below fails to catch the exception.

```c++
try
{
   plaintext_number = cryptoContext->MakePackedPlaintext(number);
}
catch (const std::exception &e)
{
    std::cerr << e.what() << std::endl;
}
```

**Comment by yspolyakov** [comment]
Please ask this question in the OpenFHE discourse forum: https://openfhe.discourse.group/ The issues are only for reporting bugs, requests, etc.
