### ISSUE TITLE
Review/update unit tests for FIXED_NOISE_HRA and NOISE_FLOODING_HRA

### ISSUE THREAD

**Issue by yspolyakov** [openfheorg/openfhe-development#791]
1. Make sure unit PRE tests are added in BGV, BFV, and CKKS for FIXED_NOISE_HRA.
2. Check unit tests for NOISE_FLOODING_HRA (BGV only). Add tests for 1, 4 and 5 hops. Use pre-hra-secure as an example.

**Comment by pascoec** [comment]
adding fix for 4 hops
