### ISSUE TITLE
How to install old version 1.0.4

### ISSUE THREAD

**Issue by Sinking-Stone** [openfheorg/openfhe-development#798]
Hello, when I tried to install the older version, after I downloaded `1.0.4` and downloaded all the dependent repositories in the `third-party` directory, I got the following error after executing `make -j4`. The dependency warehouse I downloaded is the latest version, may I ask where the problem is?
![图片](https://github.com/openfheorg/openfhe-development/assets/89176650/377f7dc0-7020-40dd-9c28-db88aa14b792)
When I commented out the error there was a new error.
![图片](https://github.com/openfheorg/openfhe-development/assets/89176650/c27b1c84-a022-42ee-84e8-a5de640fba68)
my OS is 20.04.1-Ubuntu, and I have installed all the required environment dependencies.

**Comment by yspolyakov** [comment]
Please ask this question at the OpenFHE discourse forum: https://openfhe.discourse.group/ We use issues for bug reports/feature requests.
