### ISSUE TITLE
Incorrect documentation for PKE/keyswitching

### ISSUE THREAD

**Issue by iquah1** [openfheorg/openfhe-development#8]
1) [Keyswitching](https://github.com/openfheorg/openfhe-development/tree/main/src/pke/include/keyswitch) documentation is stale for [keyswitch-bv.h](https://github.com/openfheorg/openfhe-development/blob/main/src/pke/include/keyswitch/keyswitch-bv.h) and [keyswitch-hybrid.h](https://github.com/openfheorg/openfhe-development/blob/main/src/pke/include/keyswitch/keyswitch-hybrid.h). They seem to reference the documentation for the base class? 

2) Can someone confirm if the documentation of [keyswitch-BV.cpp](https://github.com/openfheorg/openfhe-development/blob/main/src/pke/lib/keyswitch/keyswitch-bv.cpp) and [keyswitch-hybrid.cpp](https://github.com/openfheorg/openfhe-development/blob/main/src/pke/lib/keyswitch/keyswitch-hybrid.cpp) and [keyswitch-rns.cpp](https://github.com/openfheorg/openfhe-development/blob/main/src/pke/lib/keyswitch/keyswitch-rns.cpp)are correct? They all have the same documentation discussing CKKS? 

```

/*
  CKKS scheme implementation
 */

 /*
Description:

This code implements RNS variants of the Cheon-Kim-Kim-Song scheme.

The CKKS scheme is introduced in the following paper:
- Jung Hee Cheon, Andrey Kim, Miran Kim, and Yongsoo Song. Homomorphic
encryption for arithmetic of approximate numbers. Cryptology ePrint Archive,
Report 2016/421, 2016. https://eprint.iacr.org/2016/421.

 Our implementation builds from the designs here:
 - Marcelo Blatt, Alexander Gusev, Yuriy Polyakov, Kurt Rohloff, and Vinod
Vaikuntanathan. Optimized homomorphic encryption solution for secure genomewide
association studies. Cryptology ePrint Archive, Report 2019/223, 2019.
https://eprint.iacr.org/2019/223.
 - Andrey Kim, Antonis Papadimitriou, and Yuriy Polyakov. Approximate
homomorphic encryption with reduced approximation error. Cryptology ePrint
Archive, Report 2020/1118, 2020. https://eprint.iacr.org/2020/
1118.
 */
```

3) Can I get a quick blurb about `keyswitch-bv` and `keyswitch-hybrid`? I don't know enough to comment on them or write documentation up.

**Comment by yspolyakov** [comment]
Adding @kimandrik to this thread. Let us discuss it during our meeting on Friday.

**Comment by iquah1** [comment]
> meeting on Friday.

Just checking - you're talking about in our weekly meeting, right?

**Comment by yspolyakov** [comment]
@iquah1 The key switching methods are described in Appendix A of https://eprint.iacr.org/2021/204 Please add short descriptions pointing to this source.
