### ISSUE TITLE
UTBFVRNS_CRT/BFVrns_FastBaseConvqToBskMontgomery sometimes seg faults

### ISSUE THREAD

**Issue by sarojaduality** [openfheorg/openfhe-development#80]
I have not been able to replicate the issue on my machine, but here is an example run where it seg faults: https://github.com/openfheorg/openfhe-development/runs/7136560551?check_suite_focus=true

**Comment by yspolyakov** [comment]
The unit test is currently commented out. Needs to be turned on before testing.

**Comment by dsuponitskiy** [comment]
a struct UnitTestCCParams was not initialized upon creation in BFVrns_FastBaseConvqToBskMontgomery() (UnitTestBFVrnsCRTOperations.cpp) as UnitTestCCParams was meant to be created using a list of values.
Added UnitTestCCParams' initialization
