### ISSUE TITLE
After performing the ReLU operation, I encounter the following error:

### ISSUE THREAD

**Issue by Little-chick** [openfheorg/openfhe-development#817]
![图片1](https://github.com/openfheorg/openfhe-development/assets/74541422/857c2e41-7004-467f-af1a-6864229eb943)
The output just before the error is:
 

![image](https://github.com/openfheorg/openfhe-development/assets/74541422/d17c0696-031e-4da7-9948-c730d0a6675e)

**Comment by Little-chick** [comment]
![image](https://github.com/openfheorg/openfhe-development/assets/74541422/5b395ed1-aa49-439b-85d9-72c0d11b76e2)
I've tried printing the noise budget before and after key operations to diagnose the problem. The noise budget remains low (2 bits) both before and after bootstrapping, and after the Chebyshev approximation.
Why does the noise budget remain at 2 bits even after bootstrapping?
Why does decryption fail due to a high approximation error?
What parameters should I check or adjust to resolve this issue?

**Comment by yspolyakov** [comment]
Please ask this question at https://openfhe.discourse.group/ We use Issues only for reporting bugs/request new features. When you create a topic at the Discourse forum, please also include a minimal working example. It seems like you are getting an incorrect result because of the input.
