### ISSUE TITLE
Some questions about GPU acceletarion

### ISSUE THREAD

**Issue by summer-xrx** [openfheorg/openfhe-development#848]
Hello, I am very curious about GPU acceletarion. I have noticed that GPU acceleration has not yet been implemented in many mainstream fully homomorphic encryption libraries. Now, I have the following questions:
1. Why can't GPU acceleration be implemented in those mainstream libraries now? 
2. What are the technical challenges of using GPU to accelerate homomorphic encryption? 
3. Compared to other mainstream FHE libraries, what are the advantages of your library?
Looking forward to your reply, thank you!

**Comment by yspolyakov** [comment]
Please ask your questions at https://openfhe.discourse.group/ I think it is better to separate your questions in two topics there (1 and 2nd question, and separately the 3rd question).
