### ISSUE TITLE
g++ compiler

### ISSUE THREAD

**Issue by AniD-z** [openfheorg/openfhe-development#858]
I know this is a noobie question but please provide the g++ command line code which includes the g++ -l -I to compile a new cpp file i have written ,im getting a lot of errors doing it myself after manually including all the packages .
![image](https://github.com/user-attachments/assets/9da6b10f-8b5f-4a03-a21b-88e41bcf5356)

**Comment by dsuponitskiy** [comment]
You may be able to find some answers by searching [the OpenFHE forum](https://openfhe.discourse.group/). We encourage OpenFHE users to post their questions there.
For your question: you may find some answers on this [documentation page](https://openfhe-development.readthedocs.io/en/latest/sphinx_rsts/intro/building_user_applications.html).
